version: '3'

services:
  jenkins:
    image: jenkins/jenkins:2.345-alpine
    restart: unless-stopped
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    logging:
      driver: "journald"
    extra_hosts:
      - "host.docker.internal:${JENKINS_HOST_IP}"

  nginx:
    image: nginx:1.20.1-alpine
    restart: unless-stopped
    volumes:
      - nginx_logs:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - ${JENKINS_HOST_PORT}:443
    environment:
      - SERVER_NAME=${DOMAIN_NAME}
      - HOST_PORT=${JENKINS_HOST_PORT}
    command: /bin/sh -c "envsubst '$$SERVER_NAME $$HOST_PORT' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    profiles:
      - maintenance

volumes:
  jenkins_home:
  nginx_logs:
